// #include "canvas/Persistency/Common/Wrapper.h"

#include "larcorealg/GeoAlgo/GeoAABox.h"
#include "larcorealg/GeoAlgo/GeoAlgoConstants.h"
#include "larcorealg/GeoAlgo/GeoAlgoException.h"
#include "larcorealg/GeoAlgo/GeoAlgo.h"
#include "larcorealg/GeoAlgo/GeoAlgo-TypeDef.h"
#include "larcorealg/GeoAlgo/GeoCone.h"
#include "larcorealg/GeoAlgo/GeoCylinder.h"
#include "larcorealg/GeoAlgo/GeoDirectedLine.h"
#include "larcorealg/GeoAlgo/GeoHalfLine.h"
#include "larcorealg/GeoAlgo/GeoLine.h"
#include "larcorealg/GeoAlgo/GeoLineSegment.h"
#include "larcorealg/GeoAlgo/GeoObjCollection.h"
#include "larcorealg/GeoAlgo/GeoSphere.h"
#include "larcorealg/GeoAlgo/GeoTrajectory.h"
#include "larcorealg/GeoAlgo/GeoVector.h"
